# -*- coding: utf-8 -*-
"""code7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cw3tlkOhXmRneeeC7HtCar074wDHs6by
"""

import numpy as np
import matplotlib.pyplot as plt

#using termux
import subprocess
import  shlex
frame1=plt.gca()
x=np.linspace(0,10,1000)
y=0*x
plt.axhline(y=0,xmin=0.2,xmax=0.6,linewidth=6,color='r')
plt.plot(x,y)
plt.title('Solution marked in red')
plt.xlabel('$x$')

frame1.axes.get_yaxis().set_visible(False)
#plt.savefig('./pyfigs/ineq.eps')
#plt.ylim([0,0.1])

plt.show()