# -*- coding: utf-8 -*-
"""code3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cf7MtNc4Y25NkeoWbF92xqhKvrFTjJ38
"""

import numpy as np
import matplotlib.pyplot as plt

#Quad vertices
A = np.array([6, 0])
B = np.array([0, 8])
C = np.array([0, 0])

p = np.array([[3, -4], [1, 0]])
q = np.array([-7, 3])
O = np.sum(np.linalg.inv(p)*q , axis=1)
print(A, B, C, O)

#plot circle
circle1 = plt.Circle((O[0], O[1]), np.linalg.norm(A-O), color='b', fill=False)

fig, ax = plt.subplots()
ax.grid()
ax.add_artist(circle1)
ax.set_aspect('equal', adjustable='datalim')


#plot points and lines
ax.text(A[0], A[1] * (1 - 0.1), 'A')
ax.plot(A[0], A[1] , 'o')
ax.text(B[0], B[1] * (1 - 0.1), 'B')
ax.plot(B[0], B[1], 'o')
ax.text(C[0], C[1] * (1 + 0.1), 'C')
ax.plot(C[0], C[1], 'o')
ax.text(O[0], O[1] * (1 - 0.2), 'O')
ax.plot(O[0], O[1], 'o')

